language: bash

services:
  - docker

env:
  matrix:
    - TYPO3_VER=8.7
    - TYPO3_VER=9.5 EXTRA_TAG=latest

before_script:
  - docker pull $TRAVIS_REPO_SLUG || true

script:
  - .travis/build.sh $TRAVIS_TAG

before_deploy:
  - docker login --username "$REGISTRY_USER" --password "$REGISTRY_PASS"

deploy:
  - provider: script
    script: .travis/push.sh
    on:
      branch: master

  - provider: script
    script: .travis/push.sh dev
    on:
      branch: dev

  - provider: script
    script: .travis/push.sh $TRAVIS_TAG
    on:
      tags: true
