version: "2"

services:
  mariadb:
    image: "bitnami/mariadb"
    container_name: "mariadb"
    environment:
      - MARIADB_DATABASE=t3
      - MARIADB_USER=t3
      - MARIADB_PASSWORD=t3
      - MARIADB_ROOT_PASSWORD=toor
    volumes:
      - "mariadb-vol:/bitnami/mariadb"
    ports:
      - "127.0.0.1:3306:3306"

  typo3:
    image: "undecaf/typo3-dev"
    container_name: "typo3"
    hostname: "dev.typo3.local"
    cap_add:
      - SYS_ADMIN
    volumes:
      - "typo3-vol:/var/www/localhost"
    ports:
      - "127.0.0.1:8080:80"
    
volumes:
  mariadb-vol:
  typo3-vol:
