version: "2"

services:
  postgresql:
    image: "bitnami/postgresql"
    container_name: "postgresql"
    environment:
      - POSTGRESQL_DATABASE=t3
      - POSTGRESQL_USERNAME=t3
      - POSTGRESQL_PASSWORD=t3
    volumes:
      - "postgresql-vol:/bitnami/postgresql"
    ports:
      - "127.0.0.1:5432:5432"

  typo3:
    image: "undecaf/typo3-dev"
    container_name: "typo3"
    cap_add:
      - SYS_ADMIN
    volumes:
      - "typo3-vol:/var/www/localhost"
    ports:
      - "127.0.0.1:8080:80"
    
volumes:
  postgresql-vol:
  typo3-vol:
